<#
.SYNOPSIS
  Bootstraps the Terraform remote-state backend in Azure.

.DESCRIPTION
  Creates a dedicated resource group + storage account + container that holds
  Terraform state for the PhotoGallery dev (and later prod) environments.
  This is a one-time, manual, idempotent operation. Run once per subscription.

  Output: writes ../dev/backend.dev.hcl with the resolved storage account
  name so subsequent `terraform init -backend-config=backend.dev.hcl` works.

.PREREQS
  * Azure CLI installed and `az login` completed.
  * Logged-in principal has Contributor on the target subscription.

.PARAMETER SubscriptionId
  Target Azure subscription.

.PARAMETER Location
  Azure region (default: eastus2).

.EXAMPLE
  ./bootstrap-state.ps1 -SubscriptionId 00000000-0000-0000-0000-000000000000
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$SubscriptionId,

    [string]$Location = "eastus2",

    [string]$ResourceGroupName = "rg-photogallery-tfstate",

    [string]$ContainerName = "tfstate"
)

$ErrorActionPreference = "Stop"

Write-Host "Setting subscription..." -ForegroundColor Cyan
az account set --subscription $SubscriptionId | Out-Null

# Storage account names must be globally unique, 3-24 lowercase alnum.
# Use a 6-char hash of the subscription so reruns hit the same name.
$hashSource = "$SubscriptionId-pgtfstate"
$sha = [System.Security.Cryptography.SHA256]::Create()
$bytes = [System.Text.Encoding]::UTF8.GetBytes($hashSource)
$hash = ($sha.ComputeHash($bytes) | ForEach-Object { $_.ToString("x2") }) -join ""
$suffix = $hash.Substring(0, 6)
$storageAccountName = "stpgtfstate$suffix"

Write-Host "Resource group : $ResourceGroupName" -ForegroundColor Yellow
Write-Host "Storage account: $storageAccountName" -ForegroundColor Yellow
Write-Host "Container      : $ContainerName"      -ForegroundColor Yellow
Write-Host "Location       : $Location"           -ForegroundColor Yellow

Write-Host "`nCreating resource group..." -ForegroundColor Cyan
az group create --name $ResourceGroupName --location $Location --tags project=PhotoGallery purpose=tfstate | Out-Null

Write-Host "Creating storage account (idempotent)..." -ForegroundColor Cyan
az storage account create `
    --name $storageAccountName `
    --resource-group $ResourceGroupName `
    --location $Location `
    --sku Standard_LRS `
    --kind StorageV2 `
    --encryption-services blob `
    --min-tls-version TLS1_2 `
    --allow-blob-public-access false `
    --tags project=PhotoGallery purpose=tfstate | Out-Null

Write-Host "Enabling blob versioning + soft-delete..." -ForegroundColor Cyan
az storage account blob-service-properties update `
    --account-name $storageAccountName `
    --resource-group $ResourceGroupName `
    --enable-versioning true `
    --enable-delete-retention true `
    --delete-retention-days 30 | Out-Null

Write-Host "Granting current user 'Storage Blob Data Contributor' on the state account..." -ForegroundColor Cyan
$userObjectId = az ad signed-in-user show --query id -o tsv
$saId = az storage account show --name $storageAccountName --resource-group $ResourceGroupName --query id -o tsv
az role assignment create `
    --assignee-object-id $userObjectId `
    --assignee-principal-type User `
    --role "Storage Blob Data Contributor" `
    --scope $saId 2>$null | Out-Null

Write-Host "Creating state container (using AAD auth)..." -ForegroundColor Cyan
# Tiny pause so the role assignment propagates
Start-Sleep -Seconds 15
az storage container create `
    --name $ContainerName `
    --account-name $storageAccountName `
    --auth-mode login | Out-Null

# Emit backend.dev.hcl next to terraform/dev/main.tf
$backendPath = Join-Path $PSScriptRoot "..\dev\backend.dev.hcl"
$backendContent = @"
# Auto-generated by terraform/bootstrap/bootstrap-state.ps1 — do not commit.
resource_group_name  = "$ResourceGroupName"
storage_account_name = "$storageAccountName"
container_name       = "$ContainerName"
key                  = "dev.tfstate"
use_azuread_auth     = true
"@
$backendContent | Set-Content -Path $backendPath -Encoding utf8
Write-Host "`nWrote $backendPath" -ForegroundColor Green

Write-Host "`nDone. Next:" -ForegroundColor Green
Write-Host "  cd terraform/dev"
Write-Host "  terraform init -backend-config=backend.dev.hcl"
Write-Host "  cp terraform.tfvars.example terraform.tfvars   # then edit"
Write-Host "  terraform plan -out=dev.tfplan"
Write-Host "  terraform apply dev.tfplan"
